example.type=json
example.timeout=3000
example.delay=1000
example.systemName=Hubble
SrvGetAutoSubscriptionList.type=json
SrvGetAutoSubscriptionList.timeout=3000
SrvGetAutoSubscriptionList.delay=1000
SrvGetAutoSubscriptionList.systemName=system