example.type=json
example.timeout=3000
example.delay=1000
example.systemName=Hubble
SrvGetAutoSubscriptionList.type=json
SrvGetAutoSubscriptionList.timeout=5000
SrvGetAutoSubscriptionList.delay=2000
SrvGetAutoSubscriptionList.systemName=sssss