##influxdb.username=metrics_cs
##influxdb.password=LTsud45
##influxdb.batch.byCount=1000
##influxdb.batch.byTimeInMs=60000
##influxdb.database=mock_metrics_cs
##???????? ?? ???? subsystem
##influxdb.subsystem=CREATE_SUBSYSTEM
#influxdb.block=B1
##influxdb.chanel=channel
#influxdb.connect.url=http://localhost:8480/insert/01/influx/write
##influxdb.retentionpolicy=autogen